export type {
	SeparatorProps as AutocompleteSeparatorProps,
	SeparatorState as AutocompleteSeparatorState,
} from "@base-ui/react/separator"

export type {
	AutocompleteRootProps,
	AutocompleteRootState,
	AutocompleteRootActions,
	AutocompleteRootChangeEventReason,
	AutocompleteRootChangeEventDetails,
	AutocompleteRootHighlightEventReason,
	AutocompleteRootHighlightEventDetails,
	AutocompleteInputGroupProps,
	AutocompleteInputGroupState,
	AutocompleteInputProps,
	AutocompleteInputState,
	AutocompleteTriggerProps,
	AutocompleteTriggerState,
	AutocompleteIconProps,
	AutocompleteIconState,
	AutocompleteClearProps,
	AutocompleteClearState,
	AutocompleteValueProps,
	AutocompleteValueState,
	AutocompletePortalProps,
	AutocompletePortalState,
	AutocompleteBackdropProps,
	AutocompleteBackdropState,
	AutocompletePositionerProps,
	AutocompletePositionerState,
	AutocompletePopupProps,
	AutocompletePopupState,
	AutocompleteArrowProps,
	AutocompleteArrowState,
	AutocompleteStatusProps,
	AutocompleteStatusState,
	AutocompleteEmptyProps,
	AutocompleteEmptyState,
	AutocompleteListProps,
	AutocompleteListState,
	AutocompleteRowProps,
	AutocompleteRowState,
	AutocompleteItemProps,
	AutocompleteItemState,
	AutocompleteGroupProps,
	AutocompleteGroupState,
	AutocompleteGroupLabelProps,
	AutocompleteGroupLabelState,
	AutocompleteCollectionProps,
	AutocompleteCollectionState,
	AutocompleteFilter,
	AutocompleteFilterOptions,
} from "@base-ui/react/autocomplete"