import { createMenuHandle } from "./menu.utils"

import {
	MenuRoot,
	MenuTrigger,
	MenuPortal,
	MenuBackdrop,
	MenuPositioner,
	MenuPopup,
	MenuArrow,
	MenuViewport,
	MenuItem,
	MenuLinkItem,
	MenuSeparator,
	MenuSubmenuRoot,
	MenuSubmenuTrigger,
	MenuGroup,
	MenuGroupLabel,
	MenuRadioGroup,
	MenuRadioItem,
	MenuRadioItemIndicator,
	MenuCheckboxItem,
	MenuCheckboxItemIndicator,
} from "./menu"

export const Menu = {
	Root: MenuRoot,
	Trigger: MenuTrigger,
	Portal: MenuPortal,
	Backdrop: MenuBackdrop,
	Positioner: MenuPositioner,
	Popup: MenuPopup,
	Arrow: MenuArrow,
	Viewport: MenuViewport,
	Item: MenuItem,
	LinkItem: MenuLinkItem,
	Separator: MenuSeparator,
	Submenu: MenuSubmenuRoot,
	SubmenuTrigger: MenuSubmenuTrigger,
	Group: MenuGroup,
	GroupLabel: MenuGroupLabel,
	RadioGroup: MenuRadioGroup,
	RadioItem: MenuRadioItem,
	RadioItemIndicator: MenuRadioItemIndicator,
	CheckboxItem: MenuCheckboxItem,
	CheckboxItemIndicator: MenuCheckboxItemIndicator,
	createHandle: createMenuHandle,
} as const