export type {
	SliderRootProps,
	SliderRootState,
	SliderRootChangeEventReason,
	SliderRootChangeEventDetails,
	SliderRootChangeEventCustomProperties,
	SliderRootCommitEventReason,
	SliderRootCommitEventDetails,
	SliderLabelProps,
	SliderLabelState,
	SliderValueProps,
	SliderValueState,
	SliderControlProps,
	SliderControlState,
	SliderTrackProps,
	SliderTrackState,
	SliderIndicatorProps,
	SliderIndicatorState,
	SliderThumbProps,
	SliderThumbState,
	ThumbMetadata,
} from "@base-ui/react/slider"