import {
	SelectRoot,
	SelectLabel,
	SelectTrigger,
	SelectValue,
	SelectIcon,
	SelectPortal,
	SelectBackdrop,
	SelectPositioner,
	SelectPopup,
	SelectArrow,
	SelectList,
	SelectItem,
	SelectItemText,
	SelectItemIndicator,
	SelectSeparator,
	SelectGroup,
	SelectGroupLabel,
} from "./select"

export const Select = {
	Root: SelectRoot,
	Label: SelectLabel,
	Trigger: SelectTrigger,
	Value: SelectValue,
	Icon: SelectIcon,
	Portal: SelectPortal,
	Backdrop: SelectBackdrop,
	Positioner: SelectPositioner,
	Popup: SelectPopup,
	Arrow: SelectArrow,
	List: SelectList,
	Item: SelectItem,
	ItemText: SelectItemText,
	ItemIndicator: SelectItemIndicator,
	Separator: SelectSeparator,
	Group: SelectGroup,
	GroupLabel: SelectGroupLabel,
} as const