import {
	ContextMenuRoot,
	ContextMenuTrigger,
	ContextMenuPortal,
	ContextMenuBackdrop,
	ContextMenuPositioner,
	ContextMenuPopup,
	ContextMenuArrow,
	ContextMenuItem,
	ContextMenuLinkItem,
	ContextMenuSeparator,
	ContextMenuSubmenuRoot,
	ContextMenuSubmenuTrigger,
	ContextMenuGroup,
	ContextMenuGroupLabel,
	ContextMenuRadioGroup,
	ContextMenuRadioItem,
	ContextMenuRadioItemIndicator,
	ContextMenuCheckboxItem,
	ContextMenuCheckboxItemIndicator,
} from "./context-menu"

export const ContextMenu = {
	Root: ContextMenuRoot,
	Trigger: ContextMenuTrigger,
	Portal: ContextMenuPortal,
	Backdrop: ContextMenuBackdrop,
	Positioner: ContextMenuPositioner,
	Popup: ContextMenuPopup,
	Arrow: ContextMenuArrow,
	Item: ContextMenuItem,
	LinkItem: ContextMenuLinkItem,
	Separator: ContextMenuSeparator,
	Submenu: ContextMenuSubmenuRoot,
	SubmenuTrigger: ContextMenuSubmenuTrigger,
	Group: ContextMenuGroup,
	GroupLabel: ContextMenuGroupLabel,
	RadioGroup: ContextMenuRadioGroup,
	RadioItem: ContextMenuRadioItem,
	RadioItemIndicator: ContextMenuRadioItemIndicator,
	CheckboxItem: ContextMenuCheckboxItem,
	CheckboxItemIndicator: ContextMenuCheckboxItemIndicator,
} as const