export type { SeparatorProps as ComboboxSeparatorProps } from "@base-ui/react/separator"

export type {
	ComboboxRootProps,
	ComboboxLabelProps,
	ComboboxInputGroupProps,
	ComboboxInputProps,
	ComboboxTriggerProps,
	ComboboxIconProps,
	ComboboxClearProps,
	ComboboxValueProps,
	ComboboxChipsProps,
	ComboboxChipProps,
	ComboboxChipRemoveProps,
	ComboboxPortalProps,
	ComboboxBackdropProps,
	ComboboxPositionerProps,
	ComboboxPopupProps,
	ComboboxArrowProps,
	ComboboxStatusProps,
	ComboboxEmptyProps,
	ComboboxListProps,
	ComboboxRowProps,
	ComboboxItemProps,
	ComboboxItemIndicatorProps,
	ComboboxGroupProps,
	ComboboxGroupLabelProps,
	ComboboxCollectionProps,
} from "@base-ui/react/combobox"