import { useComboboxFilter, useComboboxFilteredItems } from "./combobox.hooks"

import {
	ComboboxRoot,
	ComboboxLabel,
	ComboboxInputGroup,
	ComboboxInput,
	ComboboxTrigger,
	ComboboxIcon,
	ComboboxClear,
	ComboboxValue,
	ComboboxChips,
	ComboboxChip,
	ComboboxChipRemove,
	ComboboxPortal,
	ComboboxBackdrop,
	ComboboxPositioner,
	ComboboxPopup,
	ComboboxArrow,
	ComboboxStatus,
	ComboboxEmpty,
	ComboboxList,
	ComboboxRow,
	ComboboxItem,
	ComboboxItemIndicator,
	ComboboxSeparator,
	ComboboxGroup,
	ComboboxGroupLabel,
	ComboboxCollection,
} from "./combobox"

export const Combobox = {
	Root: ComboboxRoot,
	Label: ComboboxLabel,
	InputGroup: ComboboxInputGroup,
	Input: ComboboxInput,
	Trigger: ComboboxTrigger,
	Icon: ComboboxIcon,
	Clear: ComboboxClear,
	Value: ComboboxValue,
	Chips: ComboboxChips,
	Chip: ComboboxChip,
	ChipRemove: ComboboxChipRemove,
	Portal: ComboboxPortal,
	Backdrop: ComboboxBackdrop,
	Positioner: ComboboxPositioner,
	Popup: ComboboxPopup,
	Arrow: ComboboxArrow,
	Status: ComboboxStatus,
	Empty: ComboboxEmpty,
	List: ComboboxList,
	Row: ComboboxRow,
	Item: ComboboxItem,
	ItemIndicator: ComboboxItemIndicator,
	Separator: ComboboxSeparator,
	Group: ComboboxGroup,
	GroupLabel: ComboboxGroupLabel,
	Collection: ComboboxCollection,
	useFilter: useComboboxFilter,
	useFilteredItems: useComboboxFilteredItems,
} as const