export type {
	TabsRootProps,
	TabsRootState,
	TabsRootOrientation,
	TabsRootChangeEventReason,
	TabsRootChangeEventDetails,
	TabsListProps,
	TabsListState,
	TabsTabProps,
	TabsTabState,
	TabsTabSize,
	TabsTabValue,
	TabsTabPosition,
	TabsTabMetadata,
	TabsTabActivationDirection,
	TabsIndicatorProps,
	TabsIndicatorState,
	TabsPanelProps,
	TabsPanelState,
	TabsPanelMetadata,
} from "@base-ui/react/tabs"